#!/usr/bin/env node

'use strict';

//console.log("hello world");
var c = require("skilstak-colors");
var out = process.stdout;

out.write(c.clear);
while (true) {
out.write(c.rc() + "Hello World" + c.x );
}
