#!/usr/bin/env node

'use strict'
var c = require('skilstak-colors');

var printPlain = function (name) {
  console.log(name);
}

var printBlue = function (name) {
  console.log(c.clear + c.blue + name + c.x);
}

var printMulti = function (name) {
  while (true) {
    console.log(c.multi(name));
  }
}

var firstArg = process.argv[2];

printMulti(firstArg); 
