#!/usr/bin/env python3

import skilstak.colors as c
import time

def plain():
    """Clears screen and prints 'Hello World."""
    print(c.clear + c.rc() +  "Hello World" + c.reset)

def hello(kind='plain'):
    """Main 'Hello World' function"""
    try:
        if kind == 'color':
            color()
        elif kind.startswith('m'):
            multi()
        else:
            plain()    
    except KeyboardInterrupt:
        return

if __name__ == '__main__':
    import sys
    if len(sys.argv) ==1:
        hello()
    else:
        hello(sys.argv[1])
