#!/usr/bin/env python3
if __name__ == '__main__':
    import hello as h
    who, option = h.parse_args()
    message = 'hello ' + who + '!'

    try:
        if option == "-m":
            h.print_multi(message)
        elif option == "-c":
            h.print_color(message)
        else:
            h.print_plain(message)
    except KeyboardInterrupt:
        exit()


